#modified from plewis.github.io to darsenault.github.io
#modified from the latter.

title: Sophia Gosselin  
email: sophiagosselin9@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A personal page and repository
baseurl: "" # the subpath of your site, e.g. /blog

header_pages:
   - about.md
   - research.md

#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  sophiagosselin

# Build settings
markdown: kramdown
theme: minima
#theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  - jekyll-gist
  - jemoji

  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#if you ever want to add color to your text, you can use the following: 
#<span style="color:blue">some *blue* text</span>.

#modified from plewis.github.ios
